import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

final ValueNotifier<Locale> appLocale = ValueNotifier(const Locale('en'));

const Map<String, String> _arabicTranslations = {
  'Home': 'الرئيسية',
  'Plan': 'الخطة',
  'Log': 'السجل',
  'Planning': 'تخطيط',
  'Progress': 'التقدم',
  'Settings': 'الإعدادات',
  'Back': 'رجوع',
  'Good morning, Mahmoud 👋': 'صباح الخير، محمود 👋',
  'Sunday, 23 August': 'الأحد، 23 أغسطس',
  "Today's Progress": 'تقدم اليوم',
  "Today's Details": 'تفاصيل اليوم',
  "Today's Insight": 'نصيحة اليوم',
  'Details': 'التفاصيل',
  'Previous day': 'اليوم السابق',
  'Next day': 'اليوم التالي',
  'more': 'أخرى',
  'View all nutrients': 'عرض جميع العناصر الغذائية',
  'View targets': 'عرض الأهداف',
  'Water': 'الماء',
  'Hydration': 'ترطيب الجسم',
  'Log Water': 'تسجيل الماء',
  'Add Food': 'إضافة طعام',
  'Add food': 'إضافة طعام',
  'Log Meal': 'تسجيل الوجبة',
  'Edit Meal': 'تعديل الوجبة',
  'Remove Breakfast?': 'هل تريد إزالة الفطور؟',
  "This meal will be removed from today's plan.":
      'ستتم إزالة هذه الوجبة من خطة اليوم.',
  'Remove': 'إزالة',
  'Edit serving': 'تعديل الحصة',
  'Remove from meal': 'إزالة من الوجبة',
  'Plan this meal for your day': 'خطط لهذه الوجبة ليومك',
  'Meal Time': 'وقت الوجبة',
  'Whole Wheat Bread': 'خبز القمح الكامل',
  'Skip Meal': 'تخطي الوجبة',
  'Meal logging is coming soon': 'تسجيل الوجبة قادم قريبًا',
  'More actions are coming soon': 'خيارات إضافية قادمة قريبًا',
  'Calendar is coming soon': 'التقويم قادم قريبًا',
  'Foods in this meal': 'الأطعمة في هذه الوجبة',
  'Edit meal': 'تعديل الوجبة',
  'Impact on your day': 'أثرها على يومك',
  'You have remaining': 'لديك متبقٍ',
  'This meal uses': 'تستهلك هذه الوجبة',
  'After this meal': 'بعد هذه الوجبة',
  'Remaining Budget': 'المبلغ المتبقي',
  'Suggested next meal': 'الوجبة التالية المقترحة',
  'You can still have a ~500-600 kcal dinner.':
      'ما زال بإمكانك تناول عشاء بقيمة تقارب 500-600 Kcal.',
  'Good': 'جيد',
  'Moderate': 'متوسط',
  'Other Nutrients': 'مكونات غذائية أخرى',
  'Learn more': 'اعرف المزيد',
  'Calories by Meal': 'السعرات الحرارية حسب الوجبة',
  'Consumed': 'المستهلك',
  'Goal': 'الهدف',
  'of goal': 'من الهدف',
  '67% of daily goal': '67% من الهدف اليومي',
  '600 kcal remaining': '600 Kcal متبقية',
  '1.1 L remaining': '1.1 لتر متبقي',
  '+250 ml': '+250 مل',
  '+500 ml': '+500 مل',
  '+1 L': '+1 لتر',
  'Planned': 'مخطط',
  'Planned for 5:30 PM': 'مخطط في 5:30 مساءً',
  'Total': 'الإجمالي',
  'Breakfast': 'الفطور',
  'Lunch': 'الغداء',
  'Snack': 'وجبة خفيفة',
  'Dinner': 'العشاء',
  'Macronutrients': 'العناصر الغذائية الكبرى',
  'Fiber': 'الألياف',
  'Sugar': 'السكر',
  'Saturated Fat': 'الدهون المشبعة',
  'Sodium': 'الصوديوم',
  'You\'re doing well on calories, but you\'re still 45g short on protein. Consider a high-protein dinner.':
      'أنت تقوم بشكل جيد مع السعرات الحرارية، لكنك ما زلت بحاجة إلى 45 جرامًا من البروتين. فكر في عشاء غني بالبروتين.',
  'Next Meal': 'الوجبة التالية',
  'Eaten': 'تم تناولها',
  'Mark as eaten': 'تم تناولها',
  'Remaining': 'المتبقي',
  'More options': 'خيارات إضافية',
  'Calories': 'السعرات الحرارية',
  'Protein': 'البروتين',
  'Carbs': 'الكربوهيدرات',
  'Carbohydrates': 'الكربوهيدرات',
  'Fats': 'الدهون',
  'Fat': 'الدهون',
  'Add Food is coming soon': 'إضافة الطعام قادمة قريبًا',
  'Log Water is coming soon': 'تسجيل الماء قادم قريبًا',
  "Today's Plan": 'خطة اليوم',
  'Edit Plan': 'تعديل الخطة',
  'Plan your meals. Stay on track.': 'خطط لوجباتك وحافظ على تقدمك.',
  'Log Food': 'سجل الطعام',
  'Track what you eat': 'تابع ما تأكله',
  'Search for a food, brand or meal': 'ابحث عن طعام أو علامة أو وجبة',
  'Logged Today': 'المسجل اليوم',
  'items': 'عناصر',
  'Suggestions for you': 'اقتراحات لك',
  'Add More Food': 'إضافة المزيد من الطعام',
  'Track your journey. See how far you have come.':
      'تابع رحلتك وشاهد مدى تقدمك.',
  'Overview': 'نظرة عامة',
  'Nutrition': 'التغذية',
  'Trends': 'الاتجاهات',
  '7 Days': '7 أيام',
  '30 Days': '30 يوما',
  '3 Months': '3 أشهر',
  '6 Months': '6 أشهر',
  '1 Year': 'سنة',
  'Search and add food to your log.': 'ابحث عن الطعام وأضفه إلى سجلك.',
  'Scan': 'مسح',
  'Quick Add': 'إضافة سريعة',
  'My Foods': 'أطعميتي',
  'Brands': 'العلامات التجارية',
  'Recent Searches': 'عمليات البحث الأخيرة',
  'Clear all': 'مسح الكل',
  'Your Favorites': 'المفضلة لديك',
  'See all': 'عرض الكل',
  'Search Results': 'نتائج البحث',
  'Serving Size': 'حجم الحصة',
  'Number of Servings': 'عدد الحصص',
  'Add to Lunch': 'إضافة إلى الغداء',
  'Manage your account and preferences.': 'أدر حسابك وتفضيلاتك.',
  'Mahmoud': 'محمود',
  'Go Premium': 'الترقية إلى Premium',
  'View Plan': 'عرض الخطة',
  'Goals & Profile': 'الأهداف والملف الشخصي',
  'Goals': 'الأهداف',
  'Profile Information': 'معلومات الملف الشخصي',
  'Body Stats': 'بيانات الجسم',
  'Activity Level': 'مستوى النشاط',
  'Preferences': 'التفضيلات',
  'Units': 'الوحدات',
  'Appearance': 'المظهر',
  'Language': 'اللغة',
  'Account & Data': 'الحساب والبيانات',
  'Privacy': 'الخصوصية',
  'Backup & Restore': 'النسخ الاحتياطي والاستعادة',
  'Delete Account': 'حذف الحساب',
  'Support': 'الدعم',
  'Help Center': 'مركز المساعدة',
  'Contact Us': 'تواصل معنا',
  'About': 'حول التطبيق',
  'Calorie, macros, water and more': 'السعرات والعناصر الغذائية والماء والمزيد',
  'Update your personal details': 'حدّث بياناتك الشخصية',
  'Weight, height, activity level & more': 'الوزن والطول ومستوى النشاط والمزيد',
  'Moderately active': 'نشاط متوسط',
  'Customize your notifications': 'خصّص إشعاراتك',
  'Metric (kg, cm, kcal)': 'متري (كجم، سم، Kcal)',
  'Light mode': 'الوضع الفاتح',
  'Manage your privacy settings': 'أدر إعدادات الخصوصية',
  'Backup your data to the cloud': 'انسخ بياناتك احتياطيا إلى السحابة',
  'Permanently delete your account and data': 'احذف حسابك وبياناتك نهائيا',
  'FAQs and support articles': 'الأسئلة الشائعة ومقالات الدعم',
  'We are here to help': 'نحن هنا لمساعدتك',
  'App version 2.3.0': 'إصدار التطبيق 2.3.0',
  'English': 'الإنجليزية',
  'Arabic': 'العربية',
  'Premium': 'Premium',
  'Ingredients': 'المكونات',
  'Nutrition Details': 'تفاصيل التغذية',
  'Daily Insight': 'نصيحة اليوم',
  'History': 'السجل السابق',
  'Calendar': 'التقويم',
  'Edit': 'تعديل',
  'Edit calorie target?': 'هل تريد تعديل هدف السعرات؟',
  'You are about to edit your daily calorie target.':
      'أنت على وشك تعديل هدف السعرات الحرارية اليومي.',
  'Cancel': 'إلغاء',
  'Continue': 'متابعة',
  'Save calorie changes?': 'هل تريد حفظ تعديلات السعرات؟',
  'Your daily calorie target will be updated after saving.':
      'سيتم تحديث هدف السعرات اليومي بعد الحفظ.',
  'Save': 'حفظ',
  'Filters': 'الفلاتر',
  'Current': 'الحالي',
  'Change': 'التغيير',
  'Insights': 'الرؤى',
  "You're on track! 🎯": 'على المسار الصحيح! 🎯',
  'Log water': 'تسجيل الماء',
  'You have': 'لديك',
  'kcal remaining': 'Kcal متبقٍ',
  'Logged': 'مسجل',
  'Skipped': 'متخطى',
  'Meal Plan': 'خطة الوجبات',
  'Food List': 'قائمة الطعام',
  'Daily Targets': 'الأهداف اليومية',
  'Daily Target': 'الهدف اليومي',
  'Edit Target': 'تعديل الهدف',
  'Planned Foods': 'الأطعمة المخططة',
  'Search planned food...': 'ابحث عن طعام مخطط...',
  'Nutrition Summary': 'ملخص التغذية',
  'Meal Status': 'حالة الوجبة',
  'This meal is planned. Changes here update the plan, not your recorded intake.':
      'هذه الوجبة مخططة. التغييرات هنا تحدّث الخطة وليس السجل المسجل.',
  'Save Changes': 'حفظ التغييرات',
  'Log updated': 'تم تحديث السجل',
  "Couldn't update your log": 'تعذر تحديث سجلك',
  'Retry': 'إعادة المحاولة',
  'of your daily calories': 'من سعراتك اليومية',
  'Food Log History': 'سجل الطعام',
  'Search logged food...': 'ابحث في الطعام المسجل...',
  'Today': 'اليوم',
  'Earlier': 'سابقًا',
  'All': 'الكل',
  'foods': 'أطعمة',
  'Notifications': 'الإشعارات',
  'Mark all read': 'تحديد الكل كمقروء',
  'You\'re all caught up': 'لا توجد إشعارات جديدة',
  'No new notifications.': 'لا توجد إشعارات جديدة.',
  'Open Meal Details': 'فتح تفاصيل الوجبة',
  'Open Log Water': 'فتح تسجيل الماء',
  'Open Daily Insights': 'فتح الرؤى اليومية',
  'Open Progress': 'فتح التقدم',
  'Open Today Details': 'فتح تفاصيل اليوم',
  'Open notification': 'فتح الإشعار',
  'Targets need adjustment': 'الأهداف تحتاج إلى تعديل',
  'Your macro targets represent approximately':
      'تمثل أهداف العناصر الغذائية حوالي',
  'Go Back': 'رجوع',
  'Save Anyway': 'حفظ على أي حال',
  'Edit Daily Targets': 'تعديل الأهداف اليومية',
  'Set your daily nutrition goals': 'حدد أهدافك الغذائية اليومية',
  'These targets are used across your Home, Plan and Progress screens.':
      'تُستخدم هذه الأهداف في شاشات الرئيسية والخطة والتقدم.',
  'Target Mode': 'وضع الهدف',
  'Auto calculate': 'حساب تلقائي',
  'Based on your goal, activity and profile':
      'بناءً على هدفك ونشاطك وملفك الشخصي',
  'Custom': 'مخصص',
  'Set your calorie and macro targets manually':
      'حدد أهداف السعرات والعناصر الغذائية يدويًا',
  'Daily Calories': 'السعرات اليومية',
  'Your total daily energy target': 'إجمالي هدف الطاقة اليومي',
  'Daily protein target': 'هدف البروتين اليومي',
  'Daily carbohydrate target': 'هدف الكربوهيدرات اليومي',
  'Daily hydration target': 'هدف الترطيب اليومي',
  'Based on your profile': 'بناءً على ملفك الشخصي',
  'Lose Weight': 'إنقاص الوزن',
  'Current weight': 'الوزن الحالي',
  'Target weight': 'الوزن المستهدف',
  'Activity': 'النشاط',
  'Moderately Active': 'نشاط متوسط',
  'Save Targets': 'حفظ الأهداف',
  'Changes will update your daily plan and progress targets.':
      'ستحدّث التغييرات خطتك اليومية وأهداف التقدم.',
  'Meal Type': 'نوع الوجبة',
  'Time': 'الوقت',
  'Choose the meal type and time': 'اختر نوع الوجبة والوقت',
  'Serving size': 'حجم الحصة',
  'Save Serving': 'حفظ الحصة',
  'Premium plan preview is coming soon': 'معاينة الخطة المميزة قادمة قريبًا',
  'Lunch is coming up': 'اقترب موعد الغداء',
  'Your lunch is planned for 2:00 PM.': 'غداؤك مخطط الساعة 02:00 مساءً.',
  '10 min ago': 'منذ 10 دقائق',
  "You're behind on hydration": 'تأخرت في شرب الماء',
  "You still need 1.1 L to reach today's goal.":
      'ما زلت تحتاج إلى 1.1 لتر لتحقيق هدف اليوم.',
  '1 hour ago': 'منذ ساعة',
  "You're doing great today": 'أداؤك رائع اليوم',
  "You're on track to reach your calorie target.":
      'أنت على المسار الصحيح لتحقيق هدف السعرات.',
  '3 hours ago': 'منذ 3 ساعات',
  "You're short on protein": 'لديك نقص في البروتين',
  'You still need around 45g of protein today.':
      'ما زلت تحتاج إلى حوالي 45 جرامًا من البروتين اليوم.',
  'Yesterday': 'أمس',
  '7 day streak! 🔥': 'سلسلة 7 أيام! 🔥',
  "You've logged your meals consistently for 7 days.":
      'سجلت وجباتك بانتظام لمدة 7 أيام.',
  'Your weekly progress is ready': 'تقدمك الأسبوعي جاهز',
  'See your calorie, protein and consistency trends.':
      'شاهد اتجاهات السعرات والبروتين والالتزام.',
  'Monday': 'الإثنين',
  'More': 'المزيد',
  'Scan is coming soon': 'ميزة المسح قادمة قريبًا',
  'Barcode is coming soon': 'ميزة الباركود قادمة قريبًا',
  'Scan Meal is coming soon': 'ميزة مسح الوجبة قادمة قريبًا',
  'Quick Add is coming soon': 'الإضافة السريعة قادمة قريبًا',
  'Meals is coming soon': 'ميزة الوجبات قادمة قريبًا',
  'Favorites is coming soon': 'ميزة المفضلة قادمة قريبًا',
  'Edit is coming soon': 'ميزة التعديل قادمة قريبًا',
  'Duplicate is coming soon': 'ميزة التكرار قادمة قريبًا',
  'More is coming soon': 'المزيد من الخيارات قادم قريبًا',
  'Filters is coming soon': 'الفلاتر قادمة قريبًا',
  'Meals': 'الوجبات',
  '4 meals  •  1 snack': '4 وجبات • وجبة خفيفة',
  'Add Meal / Snack': 'إضافة وجبة / وجبة خفيفة',
  'Try adding a high-protein snack.': 'جرّب إضافة وجبة خفيفة غنية بالبروتين.',
  'Target': 'الهدف',
  'Total Consumed': 'الإجمالي المستهلك',
  'Daily Average': 'المتوسط اليومي',
  'Goal Average': 'متوسط الهدف',
  'Other': 'أخرى',
  'Weight  |  Last 30 days': 'الوزن | آخر 30 يوما',
  'Great job! You were consistent with your goals this week.':
      'عمل رائع! التزمت بأهدافك هذا الأسبوع.',
  'Cholesterol': 'الكوليسترول',
  'Carbohydrate': 'الكربوهيدرات',
  'Dietary Fiber': 'الألياف الغذائية',
  'Total Sugars': 'إجمالي السكريات',
  'Duplicate': 'تكرار',
  'Swap': 'تبديل',
  'Favorite': 'مفضلة',
  'What would you like to do?': 'ماذا تريد أن تفعل؟',
  'Portion Size': 'حجم الحصة',
  'grams': 'جرام',
  'servings': 'حصص',
  '1 serving = 300 g': 'الحصة الواحدة = 300 جرام',
  '% Daily Value*': '% من القيمة اليومية*',
  '* Percent Daily Values are based on a 2,000 calorie diet.':
      '* النسب اليومية مبنية على نظام غذائي يحتوي على 2000 Kcal.',
  '2,340 kcal more than last week': '2340 Kcal أكثر من الأسبوع الماضي',
  'Protein intake is improving': 'استهلاك البروتين يتحسن',
  'Goal hit 5 of 7 days': 'تحقق الهدف خلال 5 من 7 أيام',
  'of 1,800 kcal': 'من أصل 1800 Kcal',
  'remaining': 'متبقٍ',
  'Results for': 'نتائج',
  'Chicken Breast (Grilled)': 'صدر دجاج (مشوي)',
  'Brown Rice (Cooked)': 'أرز بني (مطبوخ)',
  'Greek Yogurt 0%': 'زبادي يوناني 0%',
  'Greek Yogurt': 'زبادي يوناني',
  '1 medium': '1 متوسطة',
  'Greek yogurt': 'زبادي يوناني',
  'Brown rice': 'أرز بني',
  'Chicken breast': 'صدر دجاج',
  'Banana': 'موز',
  'Almonds': 'لوز',
  'Grilled Chicken': 'دجاج مشوي',
  'White Rice': 'أرز أبيض',
  'Mixed Salad': 'سلطة مشكلة',
  'Olive Oil': 'زيت الزيتون',
  'Egg': 'بيض',
  'Bread': 'خبز',
  'Chicken': 'دجاج',
  'Rice': 'أرز',
  'Salad': 'سلطة',
  'Oil': 'زيت',
  'Apple': 'تفاح',
  'Tuna': 'تونة',
  'Generic': 'عام',
  'Fage': 'فاج',
  'Blue Diamond': 'بلو دايموند',
  'Total Fat': 'إجمالي الدهون',
  'Nutrition Distribution': 'توزيع التغذية',
  'You need ': 'تحتاج إلى ',
  '~45g more protein': 'حوالي 45 جراما إضافية من البروتين',
  'to reach your daily goal.': 'لتحقيق هدفك اليومي.',
  'See suggestions': 'عرض الاقتراحات',
  'Lunch  •  02:00 PM': 'الغداء • 02:00 مساءً',
  'Grilled Chicken\nwith Rice & Salad': 'دجاج مشوي\nمع أرز وسلطة',
  '4 items': '4 عناصر',
  'Barcode': 'باركود',
  'Scan Meal': 'مسح الوجبة',
  'Recent': 'الأخيرة',
  'You have ': 'لديك ',
  '2:00 PM  •  620 kcal  •  52g protein':
      '02:00 مساءً • 620 Kcal • 52 جرام بروتين',
  'Egg 100g': 'بيض 100 جرام',
  'Bread 60g': 'خبز 60 جرام',
  'Chicken 200g': 'دجاج 200 جرام',
  'Rice 150g': 'أرز 150 جرام',
  'Salad 100g': 'سلطة 100 جرام',
  'Apple 150g': 'تفاح 150 جرام',
  'Almonds 20g': 'لوز 20 جرام',
  'Tuna 120g': 'تونة 120 جرام',
  'Bread 80g': 'خبز 80 جرام',
  '420 kcal': '420 Kcal',
  '620 kcal': '620 Kcal',
  '200 kcal': '200 Kcal',
  '450 kcal': '450 Kcal',
  '28g protein': '28 جرام بروتين',
  '52g protein': '52 جرام بروتين',
  '5g protein': '5 جرام بروتين',
  '40g protein': '40 جرام بروتين',
  '52g protein  |  6g fat  |  0g carbs':
      '52 جرام بروتين | 6 جرام دهون | 0 جرام كربوهيدرات',
  '4g protein  |  0.4g fat  |  42g carbs':
      '4 جرام بروتين | 0.4 جرام دهون | 42 جرام كربوهيدرات',
  '2g protein  |  4g fat  |  6g carbs':
      '2 جرام بروتين | 4 جرام دهون | 6 جرام كربوهيدرات',
  '0g protein  |  10g fat  |  0g carbs':
      '0 جرام بروتين | 10 جرام دهون | 0 جرام كربوهيدرات',
  'Mon': 'الإثنين',
  'Tue': 'الثلاثاء',
  'Wed': 'الأربعاء',
  'Thu': 'الخميس',
  'Fri': 'الجمعة',
  'Sat': 'السبت',
  'Sun': 'الأحد',
};

class AppLocalization {
  static bool isArabic(BuildContext context) {
    final locale = appLocale.value;
    return locale.languageCode == 'ar' ||
        Localizations.localeOf(context).languageCode == 'ar';
  }

  static String text(BuildContext context, String english, String arabic) {
    return isArabic(context) ? arabic : english;
  }

  static TextDirection direction(BuildContext context) =>
      isArabic(context) ? TextDirection.rtl : TextDirection.ltr;
}

class AppLanguageScope extends StatelessWidget {
  final Widget child;

  const AppLanguageScope({super.key, required this.child});

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<Locale>(
      valueListenable: appLocale,
      builder: (context, locale, _) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          title: 'Nutrition',
          locale: appLocale.value,
          supportedLocales: const [Locale('en'), Locale('ar')],
          localizationsDelegates: const [
            GlobalMaterialLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
          ],
          theme: ThemeData(
            useMaterial3: true,
            scaffoldBackgroundColor: const Color(0xFFF7F8FC),
            fontFamily: 'Arial',
            colorScheme: ColorScheme.fromSeed(
              seedColor: const Color(0xFF5B35F5),
              brightness: Brightness.light,
            ),
            appBarTheme: const AppBarTheme(
              backgroundColor: Color(0xFFF7F8FC),
              foregroundColor: Color(0xFF17203A),
              elevation: 0,
              scrolledUnderElevation: 0,
              centerTitle: true,
            ),
            inputDecorationTheme: const InputDecorationTheme(
              filled: true,
              fillColor: Color(0xFFF1F2F6),
              border: OutlineInputBorder(
                borderSide: BorderSide.none,
                borderRadius: BorderRadius.all(Radius.circular(14)),
              ),
              enabledBorder: OutlineInputBorder(
                borderSide: BorderSide.none,
                borderRadius: BorderRadius.all(Radius.circular(14)),
              ),
              focusedBorder: OutlineInputBorder(
                borderSide: BorderSide(color: Color(0xFF5B35F5), width: 1.2),
                borderRadius: BorderRadius.all(Radius.circular(14)),
              ),
            ),
          ),
          builder: (context, child) {
            return Directionality(
              textDirection: locale.languageCode == 'ar'
                  ? TextDirection.rtl
                  : TextDirection.ltr,
              child: child!,
            );
          },
          home: child,
        );
      },
    );
  }
}

String appText(BuildContext context, String english, String arabic) =>
    AppLocalization.text(context, english, arabic);

String translateText(BuildContext context, String english) {
  return AppLocalization.isArabic(context)
      ? _arabicTranslations[english] ?? english
      : english;
}

String comingSoonText(BuildContext context, String feature) {
  return translateText(context, '$feature is coming soon');
}
